addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    - jacoco.exec
    target_paths: 7ffc2dfa-1584-41fa-850f-3bba6697f8d2
after_success:
- ' wget --content-disposition http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.7.7.201606060606/jacoco-0.7.7.201606060606.zip '
- ' unzip -o jacoco-0.7.7.201606060606.zip  '
- ' cd lib  '
- ' mv * ../  '
- ' cd ..  '
- ' chmod a+x *  '
- ' cd $PWD  '
- ' rm  ''jacoco.exec'''
- ' export JAVA_TOOL_OPTIONS=-javaagent:$PWD/jacocoagent.jar=destfile=$PWD/jacoco.exec,append=true  '
- ' travis_wait 720 mvn  test -Dmaven.test.failure.ignore=true -Djacoco.skip=true
  -Dcobertura.skip=true -Dmaven.clover.skip=true -Dmaven.javadoc.skip=true -Drat.skip=true
  -Drat.ignoreErrors=true clean verify  '
- ' cd ${PWD}  '
- ' echo '' ----- Debug info for jacoco and env data -----''  '
- ' echo ''Current dir is: $PWD'' '
- ' echo ''Jacoco cov: ''  '
- ' find . -name ''*.exec''  '
- ' echo '' ----------------------------------------------'' '
- ./df-build.sh
before_install:
- sudo apt-get update -qq
- if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm
  ia32-libs ia32-libs-multiarch > /dev/null; fi
- wget http://dl.google.com/android/android-sdk_r21.1-linux.tgz
- tar -zxf android-sdk_r21.1-linux.tgz
- export ANDROID_HOME=$PWD/android-sdk-linux
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
- android update sdk --filter platform-tools,android-16 --no-ui --force > /dev/null
branches: ''
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk7
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-dev.public-swarm.devfactory.com/travisWebHookListener?build_id=7ffc2dfa-1584-41fa-850f-3bba6697f8d2
script:
- mvn test-compile -Dgpg.skip=true -Dlicense.skip=true
- mvn test-compile -Dgpg.skip=true -Dlicense.skip=true
# Modified by Insights Service at 2016-11-27 18:55:43.002844
